"""Pydantic request/response schemas package. Re-exports every model so
`from app.schemas import CourseCard` keeps working unchanged.
"""
from .common import Archetype, Depth, Difficulty, DesignMode, Knobs, Presentation, StudioMode
from .course import (
    ArtifactA2UIOut,
    ArtifactReadingOut,
    ArtifactVersionOut,
    CourseCard,
    CourseDetail,
    CreateCourse,
    LessonOut,
    PatchA2UISectionRequest,
    PatchHtmlSectionRequest,
    RefinementRequest,
    ReviewLessonRequest,
    SaveArtifactRequest,
    ShareLinkOut,
    SharedLessonOut,
    UpdateCourse,
)
from .outline import (
    OutlineChapter,
    OutlineDoc,
    OutlineLesson,
    OutlineOut,
    OutlineReviewRequest,
)
from .insight import (
    DeleteInsightsResult,
    EventBatchResult,
    InsightPreferencesOut,
    InsightPreferencesPatch,
    InsightReport,
    InsightSummary,
    LearningEventBatchIn,
    LearningEventIn,
)
from .source import (
    CreateSourceCourse,
    CreateVideoLinkSource,
    LessonSourcePackOut,
    SourceDetail,
    SourceOut,
    SourceOutline,
    SourceRef,
    VideoCheckpoint,
    VideoCheckpointPlan,
    VideoGuideOut,
)
from .profile import LearningPreferences, ProfileHints, ProfileOut, ProfilePut
from .tutor import ChatMessage, ChatToolCall, TutorChatRequest, TutorChatResponse

__all__ = [
    "Archetype",
    "Depth",
    "Difficulty",
    "DesignMode",
    "Presentation",
    "StudioMode",
    "Knobs",
    "CreateCourse",
    "UpdateCourse",
    "LessonOut",
    "CourseCard",
    "CourseDetail",
    "RefinementRequest",
    "SaveArtifactRequest",
    "PatchA2UISectionRequest",
    "PatchHtmlSectionRequest",
    "ReviewLessonRequest",
    "ArtifactVersionOut",
    "ArtifactA2UIOut",
    "ArtifactReadingOut",
    "ShareLinkOut",
    "SharedLessonOut",
    "OutlineLesson",
    "OutlineChapter",
    "OutlineDoc",
    "OutlineOut",
    "OutlineReviewRequest",
    "SourceRef",
    "SourceOut",
    "SourceDetail",
    "SourceOutline",
    "CreateSourceCourse",
    "CreateVideoLinkSource",
    "LessonSourcePackOut",
    "VideoCheckpoint",
    "VideoCheckpointPlan",
    "VideoGuideOut",
    "ChatToolCall",
    "ChatMessage",
    "TutorChatRequest",
    "TutorChatResponse",
    "LearningEventIn",
    "LearningEventBatchIn",
    "EventBatchResult",
    "InsightReport",
    "InsightSummary",
    "InsightPreferencesOut",
    "InsightPreferencesPatch",
    "DeleteInsightsResult",
    "LearningPreferences",
    "ProfileHints",
    "ProfileOut",
    "ProfilePut",
]
